spring:
  datasource:
    # 基本属性
    name: dev
    url: jdbc:mysql://localhost:3306/shirojwt?serverTimezone=GMT%2B8&useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456sl
    # 可以不配置，根据url自动识别，建议配置
    driver-class-name: com.mysql.jdbc.Driver
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  type-aliases-package: com.sl.springbootshirojwt.entity